//counters actionTypes
const ADD_COUNTER = "ADD_COUNTER"; 
const REMOVE_LAST_COUNTER = "REMOVE_LAST_COUNTER"; 
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT"; 
const CLEAR = "CLEAR"; 

//todos actionTypes
const ADD_TODO = "ADD_TODO"; 
const REMOVE_LAST_TODO = "REMOVE_LAST_TODO"; 
const EDIT_TODO = "EDIT_TODO"; 
const DELETE_TODO = "DELETE_TODO"; 

export { ADD_COUNTER, REMOVE_LAST_COUNTER, INCREMENT, DECREMENT, CLEAR,
     ADD_TODO, REMOVE_LAST_TODO, EDIT_TODO, DELETE_TODO };